import DeleteButton from "@/components/buttons/icons/DeleteButton";
import { Buttons } from "@/components/buttons/Buttons";
export default function Home() {
  return (
    <main>
      <p>Olá!</p>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <div className="mx-6">
        <Buttons
          btnState="whiteMain"
          text="Registar Conta"
          btnSize="whiteSize"
        />
      </div>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
      <ul>x</ul>
    </main>
  );
}
